import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, relative } from "node:path";
import { pathToFileURL } from "node:url";

test("Pi discovers native resources, excludes shared skills, and resolves the default model", async (t) => {
	const root = process.cwd(), agentDir = resolve("agent");
	const core = join(execFileSync("npm", ["root", "--global"], { encoding: "utf8" }).trim(), "@earendil-works/pi-coding-agent/dist/core");
	const home = mkdtempSync(join(tmpdir(), "pi-resources-"));
	t.after(() => rmSync(home, { recursive: true, force: true }));
	const shared = join(home, ".agents/skills/should-not-load");
	mkdirSync(shared, { recursive: true });
	writeFileSync(join(shared, "SKILL.md"), "---\nname: should-not-load\ndescription: Shared skill excluded by Pi dotfiles.\n---\nSynthetic skill\n");
	process.env.HOME = home;
	process.env.PI_CODING_AGENT_DIR = agentDir;
	process.env.PI_OFFLINE = "1";
	const load = (name) => import(pathToFileURL(join(core, `${name}.js`)).href);
	const { DefaultResourceLoader } = await load("resource-loader");
	const { SettingsManager } = await load("settings-manager");
	const settings = JSON.parse(readFileSync(join(agentDir, "settings.json")));
	const loader = new DefaultResourceLoader({ cwd: home, agentDir, settingsManager: SettingsManager.inMemory(settings, { projectTrusted: false }) });
	await loader.reload();
	const { extensions, errors } = loader.getExtensions();
	assert.deepEqual(errors, []);
	const paths = extensions.map((extension) => relative(agentDir, extension.path));
	for (const path of ["extensions/ask-user-question.ts", "extensions/chrono-413-recovery.ts", "extensions/notify.ts", "extensions/statusline/index.ts", "npm/node_modules/pi-subagents/index.ts", "npm/node_modules/pi-web-access/index.ts", "npm/node_modules/@juicesharp/rpiv-todo/index.ts", "npm/node_modules/@narumitw/pi-btw/dist/index.ts"]) {
		assert.ok(paths.includes(path), `Missing extension: ${path}; loaded ${paths}`);
	}
	assert.ok(paths.every((path) => !/plan-todo|prompt-snippets|pi-plan-mode|pi-todo|pi-thinking-steps|packages\/my-pi/.test(path)));
	const tools = extensions.flatMap((extension) => [...extension.tools.keys()]);
	for (const name of ["ask_user_question", "web_search", "fetch_content", "todo"]) assert.ok(tools.includes(name), `Missing tool: ${name}`);
	for (const name of ["subagents-doctor", "todos", "btw"]) assert.ok(extensions.some((extension) => extension.commands.has(name)), `Missing command: ${name}`);
	assert.equal(new Set(tools).size, tools.length, "Duplicate tool registrations");
	const { skills, diagnostics } = loader.getSkills();
	assert.deepEqual(diagnostics.filter((entry) => entry.type === "collision"), []);
	const names = skills.map((skill) => skill.name);
	const sources = JSON.parse(readFileSync(join(root, "external-skills.json")));
	for (const name of ["pdf-reader", ...sources.flatMap((source) => Object.keys(source.skills))]) assert.ok(names.includes(name), `Missing skill: ${name}`);
	for (const name of ["should-not-load", "find-skills", "analyze-sessions"]) assert.ok(!names.includes(name), `Unexpected skill: ${name}`);
	assert.ok(skills.every((skill) => !skill.filePath.includes("/.agents/skills/")));
	assert.ok(loader.getThemes().themes.some((theme) => theme.name === "paper-light"));
	const { AuthStorage } = await load("auth-storage");
	const { ModelRuntime } = await load("model-runtime");
	const models = await ModelRuntime.create({ credentials: AuthStorage.inMemory(), modelsPath: join(agentDir, "models.json"), modelsStorePath: join(home, "models-store.json"), allowModelNetwork: false, refreshOnCreate: false });
	assert.equal(models.getError(), undefined);
	assert.ok(models.getModel(settings.defaultProvider, settings.defaultModel));
});
